### ISSUE TITLE
User Data -> Compute Engine (API 1)

### ISSUE THREAD

**Issue by jones-erin-650** [Pippin404/Software-Engineering-Fall24#12]
An API between the user and the compute engine. The user will specify a
source for the input, delimiter characters for the output, and a destination for the
output.

a. Make sure to make the source/destination general - the source could be a
local file, or it could be on a networked drive. The only guarantee you have
is that the data storage system will know how to access it

b. Allow the user to opt to use some reasonable default delimiters if they
don't wish to specify their own

**Comment by Pippin404** [comment]
Im doing this part!
